name = "watchlezi"
type = "webpack"
account_id = "77a37d339acf8213d7263e5bf351ef40"
route = 'watchlezi.atunemic.cn'
zone_id = '365f57d6577c17f5cbab2739bd3530fc'
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-10-04"

[site]
bucket = "./public" # this should point to the directory with static assets
entry-point = "workers-site"
